#!/usr/bin/env node
/*
  Builds the HTML pages from the files in content/:

    index.html                    English portfolio     (content/en.mjs)
    public/portuguese-page.html   Portuguese portfolio  (content/pt.mjs)
    resume/resume.html            source of the CV PDF  (content/resume.mjs)
    social/og-card.html           source of og-card.png, the English link preview
    social/og-card-pt.html        source of og-card-pt.png, the Portuguese one

  Shared facts (contact details, dates, figures, feature status) come from
  content/site.mjs, so each value is written once. The pages stay plain static
  HTML: nothing here runs in the visitor's browser, and the site still works
  with JavaScript off.

    node scripts/build.mjs           rewrite the pages
    node scripts/build.mjs --check   exit 1 if any page is out of date

  Plain Node, no dependencies: there is no npm install step.

  The generated files carry a "Generated" comment at the top. Edit content/ or
  this script, not the HTML, or the next build overwrites the edit.
*/
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import site from "../content/site.mjs";
import en from "../content/en.mjs";
import pt from "../content/pt.mjs";
import resume from "../content/resume.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DAY_MS = 24 * 60 * 60 * 1000;
const GENERATED = "Generated by scripts/build.mjs from content/. Edit those, not this file.";

/* ----------------------------------------------------------- Helpers */

// Attributes are always double-quoted, so an apostrophe needs no escaping.
const esc = (value) =>
  String(value).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);

// Replaces {tokens}. An unknown token stops the build, so a typo in content/
// cannot reach the page as literal "{token}" text.
function fill(text, vars, where) {
  return String(text).replace(/\{(\w+)\}/g, (match, key) => {
    if (!(key in vars)) throw new Error(`Unknown {${key}} in ${where}: "${text}"`);
    return vars[key];
  });
}

// Dates in content/ are calendar days; read them as UTC so the result does not
// depend on the machine's time zone.
function parseDay(iso) {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d));
}

function monthYear(t, date, names) {
  return fill(t.monthYear, { month: names[date.getUTCMonth()], year: date.getUTCFullYear() }, "monthYear");
}

const decimal = (t, n) => String(n).replace(".", t.decimal);
const percent = (t, v) => (Array.isArray(v) ? `${decimal(t, v[0])}–${decimal(t, v[1])}%` : `${decimal(t, v)}%`);
const midpoint = (v) => (Array.isArray(v) ? (v[0] + v[1]) / 2 : v);

// Width and height from a PNG or WebP file's header, so the size each page
// declares for an image follows the file when the image is replaced.
function imageSize(file) {
  const buf = readFileSync(path.join(ROOT, file));
  if (buf.toString("latin1", 1, 4) === "PNG") {
    return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
  }
  if (buf.toString("latin1", 0, 4) === "RIFF" && buf.toString("latin1", 8, 12) === "WEBP") {
    const chunk = buf.toString("latin1", 12, 16);
    if (chunk === "VP8X") return { width: 1 + buf.readUIntLE(24, 3), height: 1 + buf.readUIntLE(27, 3) };
    if (chunk === "VP8 ") return { width: buf.readUInt16LE(26) & 0x3fff, height: buf.readUInt16LE(28) & 0x3fff };
    if (chunk === "VP8L") {
      const bits = buf.readUInt32LE(21);
      return { width: 1 + (bits & 0x3fff), height: 1 + ((bits >>> 14) & 0x3fff) };
    }
  }
  throw new Error(`${file}: cannot read its size (PNG and WebP only)`);
}

// The browser-UI colour each page asks for (<meta name="theme-color">) is its
// background, read from the palette in public/main.css so the two cannot
// drift apart.
const CSS = readFileSync(path.join(ROOT, "public/main.css"), "utf8");
function paletteColour(name) {
  const match = CSS.match(new RegExp(`--${name}:\\s*(\\d+)\\s*,\\s*(\\d+)\\s*,\\s*(\\d+)\\s*;`));
  if (!match) throw new Error(`public/main.css has no --${name} channel list`);
  return `#${match.slice(1, 4).map((c) => Number(c).toString(16).padStart(2, "0")).join("")}`;
}

// Every value a {token} can name, for one language.
function valuesFor(t) {
  const f = site.femabras;
  const firstCommit = parseDay(f.firstCommit);
  const firstRelease = parseDay(f.firstRelease);
  const b = site.backtest;
  return {
    name: site.name,
    email: site.email,
    phone: site.phone.display,
    location: `${site.location.city}, ${site.location.country}`,
    timezone: site.timezone,
    productName: f.name,
    product: site.links.productLabel,
    school: site.education.school,
    gradYear: site.education.year,
    weeksToLaunch: Math.round((firstRelease - firstCommit) / (7 * DAY_MS)),
    releases: f.releases,
    releaseWindowWeeks: f.releaseWindowWeeks,
    adrs: f.adrs,
    languageCount: f.locales.length,
    launchMonth: monthYear(t, firstRelease, t.months),
    startMonth: monthYear(t, firstCommit, t.months),
    startMonthShort: monthYear(t, firstCommit, t.monthsShort),
    year: new Date().getFullYear(),
    leaguePredicted: percent(t, b.leaguePredicted),
    leagueHit: percent(t, b.leagueHit),
    tournamentPredicted: percent(t, b.tournamentPredicted),
    tournamentHit: percent(t, b.tournamentHit),
  };
}

// en.mjs and pt.mjs must have the same keys and list lengths, so the two
// pages always carry the same sections.
function assertSameShape(a, b, where = "content") {
  if (Array.isArray(a) || Array.isArray(b)) {
    if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length) {
      throw new Error(`${where}: en.mjs and pt.mjs lists differ in length`);
    }
    a.forEach((item, i) => assertSameShape(item, b[i], `${where}[${i}]`));
    return;
  }
  if (a && typeof a === "object") {
    const ka = Object.keys(a).sort().join(",");
    const kb = Object.keys(b ?? {}).sort().join(",");
    if (ka !== kb) throw new Error(`${where}: en.mjs has {${ka}}, pt.mjs has {${kb}}`);
    for (const key of Object.keys(a)) assertSameShape(a[key], b[key], `${where}.${key}`);
  }
}

/* ------------------------------------------------------------- Icons */

// One inline sprite per page: an external sprite file would not load when a
// page is opened straight from disk. Simple 24px line icons, drawn for this
// site.
const ICONS = {
  "arrow-right": '<path d="M5 12h14M13 6l6 6-6 6"/>',
  "arrow-up-right": '<path d="M7 17 17 7M8 7h9v9"/>',
  download: '<path d="M12 4v11m0 0 4.5-4.5M12 15l-4.5-4.5M5 20h14"/>',
  mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3.5 6.5 8.5 7 8.5-7"/>',
  pin: '<path d="M12 21s-7-5.6-7-11a7 7 0 0 1 14 0c0 5.4-7 11-7 11Z"/><circle cx="12" cy="10" r="2.5"/>',
  phone: '<path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2Z"/>',
  sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',
  moon: '<path d="M20 14.5A8 8 0 1 1 9.5 4a6.5 6.5 0 0 0 10.5 10.5Z"/>',
  pawn: '<circle cx="12" cy="6" r="2.6"/><path d="M9.3 10.2h5.4M10.4 10.2c0 3-1.4 5.1-2.6 7.2h8.4c-1.2-2.1-2.6-4.2-2.6-7.2M6.8 20.5h10.4M7.8 17.4h8.4v3.1H7.8z"/>',
  trending: '<path d="M3 17l6-6 4 4 7-7"/><path d="M14 8h6v6"/>',
  rocket: '<path d="M9.5 14.5 7 12c1.2-4.6 4.8-8.2 12-8.9-.6 7.1-4.3 10.8-8.9 12Z"/><circle cx="14.6" cy="9.4" r="1.6"/><path d="M7 12H4l2.4-3.2h3.3M12 17v3l3.2-2.4v-3.3M5.5 18.5c-.6.9-.9 2-.9 3 1 0 2.1-.3 3-.9"/>',
  globe: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/>',
  map: '<path d="M9 4 3 6v14l6-2 6 2 6-2V4l-6 2-6-2Z"/><path d="M9 4v14M15 6v14"/>',
  shield: '<path d="M12 3 5 6v5c0 4.5 3 8.3 7 10 4-1.7 7-5.5 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/>',
  layout: '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M9 9v11"/>',
  gamepad: '<rect x="2.5" y="7" width="19" height="11" rx="5.5"/><path d="M7 12.5h4M9 10.5v4"/><circle cx="15.5" cy="11.5" r="1"/><circle cx="17.5" cy="13.5" r="1"/>',
  "file-check": '<path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8l-5-5Z"/><path d="M14 3v5h5M9 14l2 2 4-4"/>',
  terminal: '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="m7 9 3 3-3 3M12 15h5"/>',
  music: '<path d="M9 18V5l11-2v13"/><circle cx="6.5" cy="18" r="2.5"/><circle cx="17.5" cy="16" r="2.5"/>',
  sparkles: '<path d="M11 3l1.8 4.7 4.7 1.8-4.7 1.8L11 16l-1.8-4.7L4.5 9.5l4.7-1.8Z"/><path d="M18.5 14l.8 2 2 .8-2 .8-.8 2-.8-2-2-.8 2-.8Z"/>',
  "file-text": '<path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8l-5-5Z"/><path d="M14 3v5h5M9 13h6M9 17h4"/>',
  sliders: '<path d="M4 6h10M18 6h2M4 12h4M12 12h8M4 18h12"/><circle cx="16" cy="6" r="2"/><circle cx="10" cy="12" r="2"/><circle cx="18" cy="18" r="2"/>',
  alert: '<path d="M12 3.5 2.5 20h19L12 3.5Z"/><path d="M12 10v4.5M12 17.2v.1"/>',
  search: '<circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.5 4.5"/>',
  bug: '<rect x="7" y="8" width="10" height="12" rx="5"/><path d="M12 8V5.5M9.5 5.5 11 8M14.5 5.5 13 8M3 13h4M17 13h4M4 18.5l3-1.5M20 18.5l-3-1.5M4 7.5 7 9M20 7.5 17 9M12 12v8"/>',
  "check-circle": '<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>',
  check: '<path d="m5 12.5 4.5 4.5L19 7.5"/>',
  bulb: '<path d="M9 18h6M10 21h4M12 3a6 6 0 0 0-3.5 10.9c.6.5 1 1.2 1 2.1h5c0-.9.4-1.6 1-2.1A6 6 0 0 0 12 3Z"/>',
  pen: '<path d="M4 20h4L19 9a2.8 2.8 0 0 0-4-4L4 16v4Z"/><path d="m13.5 6.5 4 4"/>',
  "list-check": '<path d="M10 6h10M10 12h10M10 18h10"/><path d="m3.5 6 1.5 1.5L7.5 5M3.5 12l1.5 1.5L7.5 11M3.5 18l1.5 1.5L7.5 17"/>',
  target: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
  cpu: '<rect x="6" y="6" width="12" height="12" rx="2"/><rect x="9.5" y="9.5" width="5" height="5" rx="1"/><path d="M9 3v3M15 3v3M9 18v3M15 18v3M3 9h3M3 15h3M18 9h3M18 15h3"/>',
  monitor: '<rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 20h8M12 16v4"/>',
  server: '<rect x="3" y="4" width="18" height="7" rx="2"/><rect x="3" y="13" width="18" height="7" rx="2"/><path d="M7 7.5h.01M7 16.5h.01"/>',
  cloud: '<path d="M7 18h10a4.5 4.5 0 0 0 .6-9A6 6 0 0 0 6.2 10 4 4 0 0 0 7 18Z"/>',
  database: '<ellipse cx="12" cy="5.5" rx="7" ry="2.5"/><path d="M5 5.5v13c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5v-13M5 12c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5"/>',
  compass: '<circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-2 5-5 2 2-5 5-2Z"/>',
  code: '<path d="m8 8-4 4 4 4M16 8l4 4-4 4M13.5 5l-3 14"/>',
  calendar: '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M8 3v4M16 3v4"/>',
  lock: '<rect x="4.5" y="10.5" width="15" height="10" rx="2"/><path d="M8 10.5V8a4 4 0 0 1 8 0v2.5"/>',
};

const icon = (name, cls = "icon") => {
  if (!ICONS[name]) throw new Error(`Unknown icon "${name}"`);
  return `<svg class="${cls}" aria-hidden="true"><use href="#i-${name}"/></svg>`;
};

const sprite = () =>
  '  <svg class="sprite" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">\n' +
  Object.entries(ICONS).map(([n, p]) => `    <symbol id="i-${n}" viewBox="0 0 24 24">${p}</symbol>`).join("\n") +
  "\n  </svg>";

// Which icon goes with which content id. Wording is in en.mjs and pt.mjs;
// live or pre-release, and the technology chips, are in site.mjs.
const HIGHLIGHT_ICONS = { chess: "pawn", predictions: "trending", releases: "rocket", languages: "globe", atmMap: "map", sessions: "lock" };
const ALSO_ICONS = { tipsterDashboard: "layout", games: "gamepad", compliance: "file-check", ownerConsole: "terminal", music: "music", assistant: "sparkles", cvBuilder: "file-text", designTokens: "sliders" };
const STEP_ICONS = ["alert", "search", "bug", "check-circle"];
const PRINCIPLE_ICONS = ["pen", "list-check", "target", "sparkles"];
const NODE_ICONS = ["monitor", "cloud", "shield", "layout", "cpu", "database"];
const SKILL_ICONS = ["monitor", "server", "cloud", "compass"];

/* ------------------------------------------------------ Portfolio page */

function portfolioPage(t, { root, pub, selfHref, otherHref, url }) {
  const v = valuesFor(t);
  const T = (text, where = "") => esc(fill(text, v, `${t.lang}.mjs ${where}`));
  const status = (id) => {
    const kind = site.status[id];
    if (kind !== "live" && kind !== "pre") throw new Error(`site.mjs status.${id} must be "live" or "pre"`);
    return kind === "live"
      ? `<span class="status status-live">${esc(t.live)}</span>`
      : `<span class="status status-pre">${esc(t.pre)}</span>`;
  };
  const cv = `${root}${site.files.cv}`;
  const cvName = site.files.cvDownloadName;
  const ogImage = site.files.ogImage[t.lang];
  const ogSize = imageSize(ogImage);
  const portraitSize = imageSize(site.files.portrait);
  const studioSize = imageSize(site.files.studio);
  const product = `${site.links.product}/${t.lang}`;
  const siteUrl = site.links.site;
  const ptUrl = `${siteUrl}public/portuguese-page.html`;
  const other = t.lang === "en" ? "pt" : "en";
  const langSwitch = t.lang === "en"
    ? `<span aria-current="true" lang="en">EN</span>\n          <a href="${otherHref}" hreflang="pt" lang="pt">PT</a>`
    : `<a href="${otherHref}" hreflang="en" lang="en">EN</a>\n          <span aria-current="true" lang="pt">PT</span>`;

  const nav = Object.entries(t.nav).map(([id, label]) => `          <li><a href="#${id}">${esc(label)}</a></li>`).join("\n");
  const tools = site.tools.map((x) => `<li>${esc(x)}</li>`).join("");

  const stats = t.stats.map((s, k) => {
    if (!(s.value in v)) throw new Error(`${t.lang}.mjs stats[${k}].value "${s.value}" is not a computed value`);
    const n = v[s.value];
    return `          <li class="stat" data-reveal style="--delay:${k * 80}ms">
            <span class="icon-tile">${icon(s.icon)}</span>
            <span><span class="stat-value"><span data-count="${n}">${n}</span>${T(s.unit, "stats")}</span><span class="stat-label">${T(s.label, "stats")}</span></span>
          </li>`;
  }).join("\n");

  const card = (id, area, body = "", delay = 0) => {
    const h = t.highlights[id];
    const tags = site.tags[id];
    if (!tags) throw new Error(`site.mjs tags.${id} is missing`);
    return `          <article class="card spotlight area-${area}" data-reveal${delay ? ` style="--delay:${delay}ms"` : ""}>
            <div class="card-top"><span class="icon-tile">${icon(HIGHLIGHT_ICONS[id])}</span>${status(id)}</div>
            <h3>${T(h.title)}</h3>
            <p>${T(h.text)}</p>${body}
            <ul class="chips">${tags.map((x) => `<li>${esc(x)}</li>`).join("")}</ul>
          </article>`;
  };

  const b = site.backtest;
  const p = t.highlights.predictions;
  const bar = (label, value, cls) =>
    `\n                <p class="bar-line"><span>${esc(label)}</span><span class="track"><span class="fill${cls ? ` ${cls}` : ""}" style="--w:${midpoint(value)}%"></span></span><span class="bar-val">${esc(percent(t, value))}</span></p>`;
  const chessBoard = `
            <div class="board" aria-hidden="true">
              ${icon("pawn", "icon piece piece-them")}
              ${icon("pawn", "icon piece piece-you")}
              <span class="move-ping">${T(t.highlights.chess.ping)}</span>
            </div>`;
  const calibration = `
            <div class="calib" data-reveal>
              <div class="calib-group">
                <p class="calib-head">${T(p.leagues)} <span class="calib-verdict verdict-off">${T(p.switchedOff)}</span></p>${bar(p.predicted, b.leaguePredicted)}${bar(p.hit, b.leagueHit, "fill-bad")}
              </div>
              <div class="calib-group">
                <p class="calib-head">${T(p.tournaments)} <span class="calib-verdict verdict-kept">${T(p.kept)}</span></p>${bar(p.predicted, b.tournamentPredicted)}${bar(p.hit, b.tournamentHit, "fill-hit")}
              </div>
            </div>`;

  const also = Object.entries(t.also).map(([id, text], k) => `          <li class="mini" data-reveal style="--delay:${(k % 4) * 60}ms">
            <span class="mini-top"><span class="icon-tile icon-tile-sm">${icon(ALSO_ICONS[id])}</span>${status(id)}</span>
            <p>${T(text, `also.${id}`)}</p>
          </li>`).join("\n");

  const d = t.debugging;
  const steps = d.steps.map((s, k) => `          <li class="step" data-reveal style="--delay:${k * 90}ms">
            <span class="step-icon">${icon(STEP_ICONS[k])}</span>
            <span class="step-num">${esc(d.step)} ${k + 1}</span>
            <h3>${T(s.title)}</h3>
            <p>${T(s.text)}</p>
          </li>`).join("\n");

  const pr = t.process;
  const principles = pr.principles.map((s, k) => `          <li class="card principle spotlight" data-reveal style="--delay:${k * 80}ms">
            <span class="icon-tile">${icon(PRINCIPLE_ICONS[k])}</span>
            <h3>${T(s.title)}</h3>
            <p>${T(s.text)}</p>
          </li>`).join("\n");
  const nodes = pr.nodes.map((n, k) =>
    `          <li class="node"><span class="icon-tile">${icon(NODE_ICONS[k])}</span><strong>${T(n.name)}</strong><span>${T(n.caption)}</span></li>`).join("\n");
  const pipeline = pr.pipeline.map((x) => `<li><span>${T(x)}</span></li>`).join("");

  const groups = t.skills.groups.map((g, k) => `          <section class="card skill-group spotlight" aria-labelledby="sk-${k}" data-reveal style="--delay:${k * 80}ms">
            <h3 id="sk-${k}"><span class="icon-tile icon-tile-sm">${icon(SKILL_ICONS[k])}</span>${T(g.name)}</h3>
            <ul class="chips">${g.items.map((x) => `<li>${T(x)}</li>`).join("")}</ul>
          </section>`).join("\n");

  const about = t.about.paragraphs.map((x) => `          <p>${T(x)}</p>`).join("\n");

  const gate = site.gate.steps.map((s) => `                <p class="t-line t-step" data-ms="${Number(s.ms) || 800}"><span class="t-state">${icon("check", "icon t-ok")}<span class="t-spin"></span></span>${esc(s.text)}${s.note ? ` <span class="t-dim">${esc(s.note)}</span>` : ""}</p>`).join("\n");

  const jsonLd = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Person",
    name: site.name,
    jobTitle: fill(t.jobTitle, v, "jobTitle"),
    url,
    email: `mailto:${site.email}`,
    image: `${siteUrl}${site.files.portrait}`,
    address: { "@type": "PostalAddress", addressLocality: site.location.city, addressCountry: site.location.countryCode },
    alumniOf: { "@type": "CollegeOrUniversity", name: site.education.school },
    sameAs: [site.links.linkedin, site.links.product],
  }, null, 2).replace(/\n/g, "\n  ");

  return `<!DOCTYPE html>
<!-- ${GENERATED} -->
<html lang="${t.htmlLang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${T(t.title)}</title>
  <meta name="description" content="${T(t.description)}">
  <meta name="author" content="${esc(site.name)}">
  <meta name="color-scheme" content="light dark">
  <meta name="theme-color" content="${paletteColour("paper-rgb")}" media="(prefers-color-scheme: light)">
  <meta name="theme-color" content="${paletteColour("night-rgb")}" media="(prefers-color-scheme: dark)">

  <link rel="canonical" href="${url}">
  <link rel="alternate" hreflang="en" href="${siteUrl}">
  <link rel="alternate" hreflang="pt" href="${ptUrl}">
  <link rel="alternate" hreflang="x-default" href="${siteUrl}">

  <meta property="og:type" content="profile">
  <meta property="og:title" content="${T(t.title)}">
  <meta property="og:description" content="${T(t.ogDescription)}">
  <meta property="og:url" content="${url}">
  <meta property="og:image" content="${siteUrl}${ogImage}">
  <meta property="og:image:width" content="${ogSize.width}">
  <meta property="og:image:height" content="${ogSize.height}">
  <meta property="og:image:alt" content="${T(t.ogImageAlt)}">
  <meta property="og:locale" content="${t.ogLocale}">
  <meta property="og:locale:alternate" content="${t.lang === "en" ? pt.ogLocale : en.ogLocale}">
  <meta name="twitter:card" content="summary_large_image">

  <link rel="icon" href="${root}${site.files.favicon}" type="image/svg+xml">
  <link rel="stylesheet" href="${pub}main.css">

  <script>
    // Runs before first paint: applies a saved theme choice and adds the .js
    // class that the reveal styles need, so without JavaScript nothing hides.
    (function () {
      var root = document.documentElement;
      root.classList.add("js");
      try {
        var saved = localStorage.getItem("theme");
        if (saved === "light" || saved === "dark") root.setAttribute("data-theme", saved);
      } catch (error) {}
    })();
  </script>
  <script src="${pub}main.js" defer></script>

  <script type="application/ld+json">
  ${jsonLd}
  </script>
</head>
<body>
${sprite()}
  <a class="skip-link" href="#main">${T(t.skip)}</a>

  <header class="site-header">
    <div class="wrap header-inner">
      <a class="brand" href="${selfHref}">
        <img class="brand-mark" src="${root}${site.files.favicon}" alt="" width="32" height="32">
        <span>${esc(site.name)}</span>
      </a>
      <nav class="site-nav" aria-label="${T(t.navLabel)}">
        <ul>
${nav}
        </ul>
      </nav>
      <div class="header-actions">
        <div class="lang-switch" role="group" aria-label="${T(t.languageLabel)}">
          ${langSwitch}
        </div>
        <button class="icon-btn" type="button" data-theme-toggle data-to-dark="${T(t.toDark)}" data-to-light="${T(t.toLight)}" aria-label="${T(t.toDark)}" hidden>
          ${icon("moon", "icon icon-moon")}
          ${icon("sun", "icon icon-sun")}
        </button>
        <a class="btn btn-ghost btn-small" href="${cv}" download="${cvName}">
          ${icon("download", "icon icon-drop")}
          ${T(t.cvShort)}
        </a>
      </div>
    </div>
  </header>

  <main id="main">

    <section class="hero" aria-labelledby="hero-title">
      <div class="hero-bg" aria-hidden="true">
        <span class="blob blob-1"></span>
        <span class="blob blob-2"></span>
        <span class="blob blob-3"></span>
        <span class="grid-bg"></span>
      </div>
      <div class="wrap">
        <div class="hero-grid">
          <div class="hero-copy">
            <p class="hello" data-reveal>${T(t.hero.hello)}</p>
            <h1 id="hero-title" data-reveal style="--delay:70ms">${T(t.hero.titleStart)} <span class="grad-text">${T(t.hero.titleEnd)}</span></h1>
            <p class="hero-sub" data-reveal style="--delay:140ms">${T(t.hero.sub)}</p>
          </div>

          <div class="hero-photo" data-reveal style="--delay:120ms">
            <div class="portrait">
              <img src="${root}${site.files.portrait}" alt="${T(t.hero.portraitAlt)}" width="${portraitSize.width}" height="${portraitSize.height}" fetchpriority="high">
            </div>
          </div>

          <div class="hero-side" data-reveal style="--delay:220ms">
            <p class="badge"><span class="pulse" aria-hidden="true"></span>${T(t.hero.badge)}</p>
            <div class="hero-actions">
              <a class="btn btn-primary" href="#work">${T(t.hero.work)} ${icon("arrow-right", "icon icon-nudge")}</a>
              <a class="btn btn-ghost" href="${cv}" download="${cvName}">${icon("download", "icon icon-drop")} ${T(t.hero.cv)}</a>
            </div>
            <ul class="hero-meta">
              <li>${icon("pin")} ${esc(v.location)} · ${esc(site.timezone)}</li>
              <li><a href="mailto:${site.email}">${icon("mail")} ${esc(site.email)}</a></li>
            </ul>
          </div>

          <div class="hero-term" data-reveal style="--delay:300ms">
            <div class="float terminal" aria-hidden="true" data-gate>
              <div class="term-bar">
                <span class="dot"></span><span class="dot"></span><span class="dot"></span>
                <span class="term-title">${esc(site.links.productLabel)}</span>
                <span class="term-live"><span class="pulse"></span>${T(t.hero.live)}</span>
              </div>
              <div class="term-body">
                <p class="t-line t-cmd"><span class="t-prompt">$</span> <span class="t-typed" data-text="${esc(site.gate.command)}">${esc(site.gate.command)}</span><span class="t-cursor"></span></p>
${gate}
                <p class="t-line t-done">${T(t.hero.gatePassed)}</p>
              </div>
            </div>
          </div>
        </div>

        <ul class="stats">
${stats}
        </ul>
      </div>
    </section>

    <div class="ticker">
      <div class="wrap ticker-inner">
        <p class="ticker-label">${T(t.stackLabel)}</p>
        <div class="marquee">
          <div class="marquee-inner">
            <ul>${tools}</ul>
            <ul aria-hidden="true">${tools}</ul>
          </div>
        </div>
      </div>
    </div>

    <section class="section" id="work" aria-labelledby="work-title">
      <div class="wrap">
        <div class="work-head">
          <div class="section-head" data-reveal>
            <p class="kicker"><b>01</b>${T(t.work.kicker)}</p>
            <h2 class="section-title" id="work-title">${esc(site.femabras.name)}</h2>
            <p class="section-lede">${T(t.work.lede)}</p>
            <ul class="pills">
              <li class="pill">${icon("calendar")}${T(t.work.since)}</li>
              <li class="pill">${icon("code")}${esc(site.femabras.stack.join(" · "))}</li>
            </ul>
          </div>
          <a class="btn btn-primary" href="${product}" target="_blank" rel="noopener" data-reveal>
            ${T(t.work.visit)} ${icon("arrow-up-right", "icon icon-nudge")}
            <span class="visually-hidden">${T(t.newTab)}</span>
          </a>
        </div>

        <div class="bento">
${card("chess", "chess", chessBoard)}

${card("predictions", "predict", calibration, 80)}

${card("releases", "release")}

${card("languages", "langs", "", 80)}

${card("atmMap", "map")}

${card("sessions", "session", "", 80)}
        </div>

        <h3 class="subhead" data-reveal>${T(t.alsoTitle)}</h3>
        <ul class="mini-grid">
${also}
        </ul>
      </div>
    </section>

    <section class="section section-alt" id="debugging" aria-labelledby="bug-title">
      <div class="wrap">
        <div class="section-head" data-reveal>
          <p class="kicker"><b>02</b>${T(d.kicker)}</p>
          <h2 class="section-title" id="bug-title">${T(d.title)}</h2>
          <p class="section-lede">${T(d.lede)}</p>
        </div>
        <ol class="timeline">
${steps}
        </ol>
        <p class="lesson" data-reveal><span class="icon-tile">${icon("bulb")}</span>${T(d.lesson)}</p>
      </div>
    </section>

    <section class="section" id="process" aria-labelledby="process-title">
      <div class="wrap">
        <div class="section-head" data-reveal>
          <p class="kicker"><b>03</b>${T(pr.kicker)}</p>
          <h2 class="section-title" id="process-title">${T(pr.title)}</h2>
        </div>
        <ol class="principles">
${principles}
        </ol>

        <h3 class="subhead" data-reveal>${T(pr.architectureTitle)}</h3>
        <ol class="flow" data-reveal>
${nodes}
        </ol>
        <div class="pipeline" data-reveal>
          <span class="pipeline-label">${T(pr.pipelineLabel)}</span>
          <ol>${pipeline}</ol>
        </div>
      </div>
    </section>

    <section class="section section-alt" id="skills" aria-labelledby="skills-title">
      <div class="wrap">
        <div class="section-head" data-reveal>
          <p class="kicker"><b>04</b>${T(t.skills.kicker)}</p>
          <h2 class="section-title" id="skills-title">${T(t.skills.title)}</h2>
        </div>
        <div class="skill-groups">
${groups}
        </div>
      </div>
    </section>

    <section class="section" id="about" aria-labelledby="about-title">
      <div class="wrap about-grid">
        <figure class="about-figure" data-reveal>
          <img src="${root}${site.files.studio}" alt="${T(t.about.studioAlt)}" width="${studioSize.width}" height="${studioSize.height}" loading="lazy" decoding="async">
          <figcaption>${T(t.about.studioCaption)}</figcaption>
        </figure>
        <div class="about-copy" data-reveal style="--delay:100ms">
          <p class="kicker"><b>05</b>${T(t.about.kicker)}</p>
          <h2 class="section-title" id="about-title">${T(t.about.title)}</h2>
${about}
        </div>
      </div>
    </section>

    <section class="section" id="contact" aria-labelledby="contact-title">
      <div class="wrap">
        <div class="contact-panel" data-reveal>
          <div>
            <p class="kicker"><b>06</b>${T(t.contact.kicker)}</p>
            <h2 class="contact-title" id="contact-title">${T(t.contact.title)}</h2>
            <p class="section-lede">${T(t.contact.lede)}</p>
            <p class="contact-note">
              <span>${icon("pin")} ${esc(v.location)} · ${esc(site.timezone)}</span>
              <a href="tel:${site.phone.tel}">${icon("phone")} ${esc(site.phone.display).replace(/ /g, "&nbsp;")}</a>
            </p>
          </div>
          <div class="contact-actions">
            <a class="btn btn-primary" href="mailto:${site.email}">${icon("mail")} ${esc(site.email)}</a>
            <a class="btn btn-ghost" href="${site.links.linkedin}" target="_blank" rel="noopener">LinkedIn ${icon("arrow-up-right", "icon icon-nudge")}<span class="visually-hidden">${T(t.newTab)}</span></a>
            <a class="btn btn-ghost" href="${cv}" download="${cvName}">${icon("download", "icon icon-drop")} ${T(t.cvShort)}</a>
          </div>
        </div>
      </div>
    </section>

  </main>

  <footer class="site-footer">
    <div class="wrap">
      <div class="footer-inner">
        <p>© <span data-year>${v.year}</span> ${esc(site.name)}</p>
        <p>${T(t.footer.note)}</p>
        <p><a href="${otherHref}" hreflang="${other}" lang="${other}">${T(t.footer.otherLanguage)}</a></p>
      </div>
    </div>
  </footer>
</body>
</html>
`;
}

/* ------------------------------------------------------------ Résumé */

function resumePage() {
  const v = valuesFor(en);
  const R = (text, where = "") => esc(fill(text, v, `resume.mjs ${where}`));
  const r = resume;
  const job = r.job;
  const ed = site.education;
  const skills = r.skills.map((s) => `      <dt>${R(s.label)}</dt>\n      <dd>${R(s.text)}</dd>`).join("\n");
  const points = job.points.map((x) => `      <li>${R(x)}</li>`).join("\n");

  return `<!DOCTYPE html>
<!-- ${GENERATED} -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>${esc(site.name)} — Résumé</title>
<meta name="author" content="${esc(site.name)}">
<!--
  Source of ${site.files.cv}. Print it to PDF after a build that changes it
  (see README.md). Styles are in resume/resume.css.

  Deliberately absent, following US hiring norms: photo, date of birth, marital
  status, full street address, school marks, references and a signed declaration.
  US employers avoid collecting these because they invite discrimination claims,
  so recruiters often set aside CVs that carry them.
-->
<link rel="stylesheet" href="resume.css">
</head>
<body>
<main class="page">

  <header>
    <h1 class="name">${esc(site.name)}</h1>
    <p class="role">${R(r.role)}</p>
    <ul class="contact">
      <li>${R(r.locationLine)}</li>
      <li><a href="mailto:${site.email}">${esc(site.email)}</a></li>
      <!-- [html-validate-disable-block tel-non-breaking -- plain spaces on purpose: some applicant-tracking parsers miss a phone number written with non-breaking spaces] -->
      <li><a href="tel:${site.phone.tel}">${esc(site.phone.display)}</a></li>
    </ul>
    <ul class="contact">
      <li>${R(r.portfolioLabel)}: <a href="${site.links.site}">${esc(site.links.siteLabel)}</a></li>
      <li>${R(r.linkedinLabel)}: <a href="${site.links.linkedin}">${esc(site.links.linkedinLabel)}</a></li>
      <li>${R(r.productLabel)}: <a href="${site.links.product}/en">${esc(site.links.productLabel)}</a></li>
    </ul>
  </header>

  <section aria-labelledby="summary">
    <h2 id="summary">${R(r.summaryTitle)}</h2>
    <p>${R(r.summary)}</p>
  </section>

  <section aria-labelledby="skills">
    <h2 id="skills">${R(r.skillsTitle)}</h2>
    <dl class="skills">
${skills}
    </dl>
  </section>

  <section aria-labelledby="experience">
    <h2 id="experience">${R(r.experienceTitle)}</h2>
    <div class="entry-head">
      <h3 class="entry-title">${R(job.title)} <span>· ${R(job.company)}</span></h3>
      <span class="dates">${R(job.dates)}</span>
    </div>
    <p class="entry-meta">${R(job.meta)}</p>
    <p class="entry-lede">${R(job.lede)}</p>
    <ul class="points">
${points}
      <li><span class="label">${R(job.preReleaseLabel)}</span> ${R(job.preRelease)}</li>
      <li>${R(job.process)}</li>
    </ul>
  </section>

  <section aria-labelledby="education">
    <h2 id="education">${R(r.educationTitle)}</h2>
    <div class="entry-head">
      <h3 class="entry-title">${esc(ed.degree)} <span>· ${esc(ed.school)}, ${esc(ed.place)}</span></h3>
      <span class="dates">${ed.year}</span>
    </div>
  </section>

  <section aria-labelledby="languages">
    <h2 id="languages">${R(r.moreTitle)}</h2>
    <p class="inline-list"><span class="label">${R(r.languagesLabel)}</span> ${R(r.languages)}</p>
    <p class="inline-list"><span class="label">${R(r.interestsLabel)}</span> ${R(r.interests)}</p>
  </section>

</main>
</body>
</html>
`;
}

/* ------------------------------------------------------- Link preview */

// The image chat apps and social sites show when a page's link is shared.
// This page is its source; README.md, "Update the link previews", says how
// to capture it. It loads the site's stylesheet in the dark theme, so the
// card uses the same palette as the pages.
function socialCard(t) {
  const v = valuesFor(t);
  const T = (text, where = "") => esc(fill(text, v, `${t.lang}.mjs ${where}`));
  const chips = site.tools.slice(0, 5).map((x) => `<li>${esc(x)}</li>`).join("");
  return `<!DOCTYPE html>
<!-- ${GENERATED} -->
<html lang="${t.htmlLang}" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=1200">
<meta name="robots" content="noindex">
<title>Link preview · ${esc(site.name)}</title>
<link rel="stylesheet" href="../public/main.css">
<style>
  /* 1200 by 630 is the size link previews are drawn for. */
  html, body { width: 1200px; height: 630px; overflow: hidden; }
  body { position: relative; }
  .og-grid {
    position: absolute;
    inset: 0;
    background-image:
      linear-gradient(var(--grid) 1px, var(--clear) 1px),
      linear-gradient(90deg, var(--grid) 1px, var(--clear) 1px);
    background-size: 48px 48px;
    -webkit-mask-image: linear-gradient(90deg, var(--clear) 35%, var(--opaque) 100%);
    mask-image: linear-gradient(90deg, var(--clear) 35%, var(--opaque) 100%);
  }
  .og-glow {
    position: absolute;
    top: -220px;
    right: -180px;
    width: 720px;
    height: 720px;
    border-radius: 50%;
    background: radial-gradient(closest-side, var(--glow-1), var(--glow-1-clear));
  }
  .og-inner {
    position: absolute;
    inset: 84px 88px;
    display: flex;
    flex-direction: column;
  }
  .og-mark { width: 64px; height: 64px; }
  .og-eyebrow {
    margin-top: 44px;
    color: var(--mint);
    font-family: var(--font-mono);
    font-size: 22px;
    font-weight: 600;
    letter-spacing: 0.08em;
    text-transform: uppercase;
  }
  .og-name { margin-top: 14px; font-size: 86px; font-weight: 700; line-height: 1; letter-spacing: -0.03em; }
  .og-tagline { margin-top: 18px; color: var(--text); font-size: 34px; font-weight: 450; }
  .og-chips { display: flex; flex-wrap: wrap; gap: 12px; margin-top: auto; }
  .og-chips li {
    padding: 8px 16px;
    border: 1px solid var(--line);
    border-radius: 999px;
    background: var(--card-solid);
    color: var(--text);
    font-family: var(--font-mono);
    font-size: 20px;
  }
</style>
</head>
<body>
<div class="og-grid"></div>
<div class="og-glow"></div>
<main class="og-inner">
  <img class="og-mark" src="../${site.files.favicon}" alt="" width="64" height="64">
  <p class="og-eyebrow">${T(t.og.eyebrow)}</p>
  <h1 class="og-name">${esc(site.name)}</h1>
  <p class="og-tagline">${T(t.og.tagline)}</p>
  <ul class="og-chips">${chips}</ul>
</main>
</body>
</html>
`;
}

/* ------------------------------------------------------------- Output */

assertSameShape(en, pt);

// `then` is the manual step a change to that page needs; the build prints it
// only when the page actually changed.
const previews = `(README.md, "Update the link previews")`;
const outputs = [
  { file: "index.html", html: portfolioPage(en, { root: "./", pub: "./public/", selfHref: "./index.html", otherHref: "./public/portuguese-page.html", url: site.links.site }) },
  { file: "public/portuguese-page.html", html: portfolioPage(pt, { root: "../", pub: "./", selfHref: "./portuguese-page.html", otherHref: "../index.html", url: `${site.links.site}public/portuguese-page.html` }) },
  { file: "resume/resume.html", html: resumePage(), then: `print it to ${site.files.cv} (README.md, "Update the résumé")` },
  { file: "social/og-card.html", html: socialCard(en), then: `capture it to ${site.files.ogImage.en} ${previews}` },
  { file: "social/og-card-pt.html", html: socialCard(pt), then: `capture it to ${site.files.ogImage.pt} ${previews}` },
];

const check = process.argv.includes("--check");
let stale = 0;
const todo = [];
for (const { file, html, then } of outputs) {
  const target = path.join(ROOT, file);
  let current = "";
  try { current = readFileSync(target, "utf8"); } catch { /* a missing page counts as changed */ }
  const changed = current !== html;
  if (check) {
    if (changed) { stale += 1; console.log(`out of date: ${file}`); }
    continue;
  }
  if (changed) {
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, html);
    if (then) todo.push(`${file} changed: ${then}.`);
  }
  console.log(`${changed ? "wrote    " : "unchanged"} ${file} (${(Buffer.byteLength(html) / 1024).toFixed(1)} KB)`);
}
if (check) {
  if (stale) {
    console.log("Run `node scripts/build.mjs` and commit the result.");
    process.exit(1);
  }
  console.log("All pages are up to date.");
} else if (todo.length) {
  console.log(["", "Still to do by hand:", ...todo.map((line) => `  ${line}`)].join("\n"));
}
